server:
  port: 9098

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    url: jdbc:mysql://127.0.0.1:3306/chess?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

websocket:
  port: 9097

github:
  client-id: xxx
  client-secret: yyy

app-url: http://192.168.1.101:9000

avatar:
  path: /avatar
  dir: /Users/avatar